### ISSUE TITLE
Height control

### ISSUE THREAD

**Issue by pellyadolfo** [nicolasjafelle/ExpandableView#1]
I have added the component to my app but I have problems controlling the height of elements. 

When expanded:

(1) header of the component moves to the top of the screen hiding anything else above the expandable, and 

(2) there is a large blank space at the bottom despite my view has android:layout_height="wrap_content"

Any way to make the component (1) not invading the space above and (2) wrapping its content?

**Comment by nicolasjafelle** [comment]
Can you post a screenshot? Also change the wrap_content to a real value like 50dp or any dp dimension that fits your needs to see if that change anything.

**Comment by pellyadolfo** [comment]
Fixed the problem with components above the expandable. It was a layout with:
            android:layout_height="0dp"
            android:layout_weight="1"
that gets collapsed when expanding ExpandableView, so nothing to do with ExpandableView itself.

Regarding the height taken by ExpandableView (which currently extends far beyond his contained panel), when height is fixed as you commented
            android:layout_height="200dp"
it takes the same height, not matter if ExpandableView is expanded or collapsed, which is not ok.

When android:layout_height="wrap_content", inner component does not wrap its inner panel, defined as:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/roomPanel"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:orientation="vertical" >
.....
</LinearLayout>
```

but extends quite beyond height of inner panel with a empty space.

The invokation in activity is:

```
// Test of Expandable View
ExpandableView expandableView = (ExpandableView)    findViewById(R.id.activity_main_top_expandable_view);
expandableView.fillData(R.drawable.button_selected_full, "My Title", false);
expandableView.addContentView(LayoutInflater.from(getBaseContext()).inflate(R.layout.roomPanel, null));
```

No idea how to control the height of inner panel to fit inner component. Working on it...

**Comment by pellyadolfo** [comment]
Copied and pasted latest source code from github instead gradle's reference
    compile 'com.github.nicolasjafelle:expandableview:1.0'
as before, but same thing is happening.

Trying to debug in method
    private ValueAnimator slideAnimator(int start, int end)
as height is worked out there.

**Comment by nicolasjafelle** [comment]
Can you send me a little project with the problem? Did you try to add the view in expandableView.addContentView() but firstly inflated?
I usually prefer to create custom view like RoomPanelview which extends some ViewGroup, it fills better for the eyes =D. 
Another tip, inflate or create the inner panel inside the ExpandableView first and then add it.

**Comment by pellyadolfo** [comment]
Hi, I think the problem is android detecting the size itself of the inner content. 
In the latest code on github, these lines:

final int widthSpec = MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED);
final int heightSpec = MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED);
contentLayout.measure(widthSpec, heightSpec);
animator = slideAnimator(0, contentLayout.getMeasuredHeight());

produces:
widthSpec = 0
heightSpec = 0
contentLayout.getMeasuredHeight() = 2862

And the last value looks to be the wrong measurement that, later, is translated as a very large blank space. 

Probably what you comment about inflating the component is relevant. I am trying combinations of these..... Will try your suggestions and update the thread.

**Comment by pellyadolfo** [comment]
Hi Nicolas, as you commented, inflating the view on a ViewGroup sets right dimensions and ExpandableView works as a charm. My final code is:

```
ExpandableView expandableView = (ExpandableView) findViewById(R.id.activity_main_top_expandable_view);
expandableView.fillData(R.drawable.button_selected_full, "My Title", false);
expandableView.addContentView(getLayoutInflater().inflate(R.layout.view_content_room, new ExpandableView(this)));
```

which is exactly the same as above by replacing the null by new ExpandableView(this) as parent. In this case I think ExpandableView(this) is a dummy ViewGroup which just provides LayoutParams.

Maybe there is a more clean way to inflate but this one works for me.

I copied the ExpandableView(this) from your code example, despite your example is a bit messy with nested layouts and global variables. Maybe a simplest hello world would help

Thanks for your component and ideas.

**Comment by nicolasjafelle** [comment]
Cool!! Good news, take a look at this class: [ExpandedListItemView Class!](https://github.com/nicolasjafelle/ExpandableView/blob/master/ExpandableViewProject/app/src/main/java/com/example/expandableview/ExpandedListItemView.java)

And then in the MainActivity class check this line:

``` java
for (int i = 0; i < stringList.length; i++) {
      ExpandedListItemView itemView = new ExpandedListItemView(this);
      itemView.setText(stringList[i], showCheckbox);
      view.addContentView(itemView); // previously inflated...
} 
```

**Comment by pellyadolfo** [comment]
Thanks Nicolas

**Comment by pellyadolfo** [comment]
Hi Nicolas, as amendment to this issue. I managed to make it work as we discussed above for a Sony Xperia. The problem was with a BLU phone. I tried everything that we discussed with no luck.

However, happily I found a fix that works for both in the accepted answer of this thead: http://stackoverflow.com/questions/4668939/viewgrouptextview-getmeasuredheight-gives-wrong-value-is-smaller-than-real

So what I did was changing the line in your code

```
                    final int widthSpec = MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED);
```

for 

```
                    DisplayMetrics metrics = new DisplayMetrics();
                    WindowManager windowManager = (WindowManager) getContext().getSystemService(Context.WINDOW_SERVICE);
                    windowManager.getDefaultDisplay().getMetrics(metrics);
                    int widthSpec = MeasureSpec.makeMeasureSpec(metrics.widthPixels, MeasureSpec.AT_MOST);
```

and now works for my 2 phones.

Regards

**Comment by nicolasjafelle** [comment]
Hey!! So finally the problem was at the code! Awesome you fixed it. Is it possible to create a pull request? Thanks in advance!

**Comment by pellyadolfo** [comment]
I am using Android Studio now and I never did a pull request from it before, and I have not my projects imported in Eclipse now. 

I will do it at the earliest opportunity.
