### ISSUE TITLE
Dynamic height ContentView

### ISSUE THREAD

**Issue by pellyadolfo** [nicolasjafelle/ExpandableView#5]
Hi, I have created a custom component which adds rows when clicking a button. For example:

```
this is row1
this is row2
this is row3
button
```

when I click the button, it will show 

```
this is row1
this is row2
this is row3
this is row4
button
```

so my custom component has a dynamic height.

I have added this custom component in a LinearLayout of mine (i.e. without using ExpandableView) and the new rows are properly shown. So my custom component grows on height according to the height of contained children. Fine.

Now, when I add my component as ContentView of ExpandableView, despite the new row is added, the ContentView of ExpandableView does not increase in height so button is lost at the bottom of the ContentView.

I guess the problem is creating an onMeasure() method for ExpandableView which is able to resize dynamically when children change in size. Any experience or any idea?

**Comment by pellyadolfo** [comment]
I have added an stackoverflow question: http://stackoverflow.com/questions/34317751/expanding-parents-height-when-expandings-child-height

**Comment by pellyadolfo** [comment]
Well, the problem happens exactly in expandable-view.xml. If I add my custom component anywhere in this layout, the component extends its height properly when new children are added.

But, when I add my component (either programmately with ExpandableView API or declaratively in the XML), inside the linear layout expandable_view_content_layout, representing the ContentLayout, my custom components is not extending height anymore when new children are added.

So, it seems ExpandableView code is fixing ContentLayout height to the first value.

**Comment by pellyadolfo** [comment]
Update, by commenting out the animation it works properly. So is the animation who is fixing the ContentLayout height value (even when component is open and no animation is running) preventing my custom component to resize height by itself when children are added. Working on a fix.

**Comment by pellyadolfo** [comment]
Well, fixed. The method onAnimationUpdate was assigning intermediate values to the animation until it gets the total height. However, at the final, the total weight remains as a numeric value.

The fix is reassign at the end of the animation back to a relative value to allow the android framework perform as expected. So add these lines in method slideAnimator().

```
    animator.addListener(new AnimatorListenerAdapter() {
        @Override
        public void onAnimationEnd(Animator animation) {
            // done
            ViewGroup.LayoutParams layoutParams = contentLayout.getLayoutParams();
            layoutParams.height = ViewGroup.LayoutParams.WRAP_CONTENT;
            contentLayout.setLayoutParams(layoutParams);
        }
    });
```

**Comment by nicolasjafelle** [comment]
Hey! Thanks!! You can also create a pull request if you found it is really necessary and needs to be handle by the library.

**Comment by pellyadolfo** [comment]
Hi Nicolas, it would be a trouble for me creating the pull request since I am working in Android Studio instead Eclipse. But the fix is working and would be required for whoever needs expanding content.
